 version: "3.7"
 services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm start"
    ports:
      -  '3000:3000'
    working_dir: /app
    volumes: 
      - ./app:/app
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: 
       MYSQL_DB: flywifi
  mysql:
    image: mysql:5.7
    volumes: 
      - flywifi_mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: flywifi
      MYSQL_USER: ROOT
      MYSQL_ALLOW_EMPTY_PASSWORD: root
    ports:
        - "9906:3306"

  flywifi_server:
    container_name: php-apache
    build: ./server
    image: php:8-apache
    volumes: 
      - ./server:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql
    networks:
      - default
    environment:
      - SECRET=${SECRET}
      - SID=${SID}
      - ISSUER=${ISSUER}
      - SERVERNAME=${SERVERNAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: mysql
    depends_on:
        - mysql
    

 volumes:
   flywifi_mysql-data:
